export type UserDataType = {
  nickname: string;
  gender: string;
  birth: string;
  home: string;
  intro: string;
  tall: number;
  physical: string;
  rectal: string;
  job: string;
  grade: string;
  school: string;
  personality: string[];
  religion: string;
  bear: string;
  smoking: string;
  bloodType: string;
  race: string;
  charm: string[];
  interest: string[];
  lifeStyle: string[];
};
