enum ModalType {
  NICKNAME = "NICKNAME",
  BIRTH = "BIRTH",
  HOME = "HOME",
  INTRO = "INTRO",
  TALL = "TALL",
  PHYSICAL = "PHYSICAL",
  RECTAL = "RECTAL",
  JOB = "JOB",
  EDUCATION = "EDUCATION",
  SCHOOL = "SCHOOL",
  PERSONALITY = "PERSONALITY",
  RELIGION = "RELIGION",
  BEAR = "BEAR",
  SMOKING = "SMOKING",
  BLOOD_TYPE = "BLOOD_TYPE",
  RACE = "RACE",
  CHARM = "CHARM",
  INTEREST = "INTEREST",
  LIFESTYLE = "LIFESTYLE",
}

export default ModalType;
